# Generated by Django 3.2.6 on 2021-08-22 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Replies',
        ),
        migrations.RenameModel(
            old_name='Threads',
            new_name='Thread',
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date']},
        ),
    ]
