# Generated by Django 3.2.6 on 2021-08-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_thread_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='slug',
            new_name='thread_slug',
        ),
    ]
