# Generated by Django 3.2.6 on 2021-08-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_rename_slug_thread_thread_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_slug',
            new_name='slug',
        ),
    ]
