# Generated by Django 3.2.6 on 2021-08-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_alter_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, default='', unique_for_date='date'),
        ),
    ]
