# Generated by Django 3.2.6 on 2021-08-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0009_alter_thread_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
