# Generated by Django 3.2.6 on 2021-08-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0010_remove_thread_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replies',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='date',
            new_name='date_added',
        ),
    ]
