# Generated by Django 3.2.6 on 2021-08-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210821_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
