# Generated by Django 3.2.6 on 2021-08-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitly', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
