# Generated by Django 3.2.6 on 2021-08-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitly', '0004_trainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
