# Generated by Django 3.2.6 on 2021-08-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitly', '0005_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
