# Generated by Django 3.2.6 on 2021-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitly', '0006_testimonials_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('gmail', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('copywrite_year', models.CharField(max_length=200)),
            ],
        ),
    ]
