# Generated by Django 3.2.6 on 2021-08-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitly', '0007_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intros',
            options={'verbose_name': 'intros', 'verbose_name_plural': 'intros'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'services', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'testimonials', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AlterModelOptions(
            name='trainees',
            options={'verbose_name': 'trainees', 'verbose_name_plural': 'trainees'},
        ),
    ]
